version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    version_requirement_updates: increase_versions
    default_labels:
      - '🤖 Dependency update'
    commit_message:
      prefix: 'chore'
      include_scope: true
